### Build a developer version of the container
FROM mcr.microsoft.com/dotnet/core/sdk:2.2

RUN mkdir -p /src && \
    mkdir -p /root/.azure

### copy the source and unit tests
COPY . /src

WORKDIR /src/app

### install azure cli
RUN dotnet restore && \
apt-get update && \
apt-get install -y apt-transport-https ca-certificates curl software-properties-common libssl-dev git wget nano lsb-release jq && \
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.asc.gpg && \
CLI_REPO=$(lsb_release -cs) && \
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ ${CLI_REPO} main" > /etc/apt/sources.list.d/azure-cli.list && \
apt-get update && \
apt-get install -y azure-cli
